// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shops.DataAccess;

#nullable disable

namespace Shops.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shops.DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 10
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("Shops.DataAccess.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DE"
                        });
                });

            modelBuilder.Entity("Shops.DataAccess.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .IsUnique();

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "femmot0@squidoo.com",
                            FirstName = "Freddie",
                            LastName = "Emmot",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "kroth1@geocities.jp",
                            FirstName = "Kearney",
                            LastName = "Roth",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "drisby2@wikimedia.org",
                            FirstName = "Drusy",
                            LastName = "Risby",
                            ShopId = 3
                        },
                        new
                        {
                            Id = 4,
                            Email = "ptonsley3@engadget.com",
                            FirstName = "Penny",
                            LastName = "Tonsley",
                            ShopId = 4
                        },
                        new
                        {
                            Id = 5,
                            Email = "agiuroni4@europa.eu",
                            FirstName = "Andy",
                            LastName = "Giuroni",
                            ShopId = 5
                        },
                        new
                        {
                            Id = 6,
                            Email = "nfairham5@51.la",
                            FirstName = "Nolly",
                            LastName = "Fairham",
                            ShopId = 6
                        },
                        new
                        {
                            Id = 7,
                            Email = "kdelany6@over-blog.com",
                            FirstName = "Kissie",
                            LastName = "Delany",
                            ShopId = 7
                        },
                        new
                        {
                            Id = 8,
                            Email = "cdarby7@chron.com",
                            FirstName = "Chris",
                            LastName = "Darby",
                            ShopId = 8
                        },
                        new
                        {
                            Id = 9,
                            Email = "gsurphliss8@mit.edu",
                            FirstName = "Gnni",
                            LastName = "Surphliss",
                            ShopId = 9
                        },
                        new
                        {
                            Id = 10,
                            Email = "cvivian9@t.co",
                            FirstName = "Cory",
                            LastName = "Vivian",
                            ShopId = 10
                        },
                        new
                        {
                            Id = 11,
                            Email = "rsienea@cbslocal.com",
                            FirstName = "Raquela",
                            LastName = "Siene",
                            ShopId = 11
                        },
                        new
                        {
                            Id = 12,
                            Email = "mocannanb@livejournal.com",
                            FirstName = "Melitta",
                            LastName = "O'Cannan",
                            ShopId = 12
                        },
                        new
                        {
                            Id = 13,
                            Email = "drossc@java.com",
                            FirstName = "Derrek",
                            LastName = "Ross",
                            ShopId = 13
                        },
                        new
                        {
                            Id = 14,
                            Email = "vberardd@wordpress.com",
                            FirstName = "Vanya",
                            LastName = "Berard",
                            ShopId = 14
                        },
                        new
                        {
                            Id = 15,
                            Email = "ahancorne@cyberchimps.com",
                            FirstName = "Ario",
                            LastName = "Hancorn",
                            ShopId = 15
                        },
                        new
                        {
                            Id = 16,
                            Email = "tfranzenf@mayoclinic.com",
                            FirstName = "Trumaine",
                            LastName = "Franzen",
                            ShopId = 16
                        },
                        new
                        {
                            Id = 17,
                            Email = "cnewingg@yahoo.com",
                            FirstName = "Chalmers",
                            LastName = "Newing",
                            ShopId = 17
                        },
                        new
                        {
                            Id = 18,
                            Email = "ahardwellh@jugem.jp",
                            FirstName = "Arlen",
                            LastName = "Hardwell",
                            ShopId = 18
                        },
                        new
                        {
                            Id = 19,
                            Email = "nwimmeri@springer.com",
                            FirstName = "Neile",
                            LastName = "Wimmer",
                            ShopId = 19
                        },
                        new
                        {
                            Id = 20,
                            Email = "pcherrettj@amazon.de",
                            FirstName = "Pammi",
                            LastName = "Cherrett",
                            ShopId = 20
                        },
                        new
                        {
                            Id = 21,
                            Email = "dlindenblattk@wired.com",
                            FirstName = "Dorolice",
                            LastName = "Lindenblatt",
                            ShopId = 21
                        },
                        new
                        {
                            Id = 22,
                            Email = "koneilll@histats.com",
                            FirstName = "Klemens",
                            LastName = "O'Neill",
                            ShopId = 22
                        },
                        new
                        {
                            Id = 23,
                            Email = "aokeeffem@forbes.com",
                            FirstName = "Abbey",
                            LastName = "O'Keeffe",
                            ShopId = 23
                        },
                        new
                        {
                            Id = 24,
                            Email = "mmaccrawn@naver.com",
                            FirstName = "Marlowe",
                            LastName = "Maccraw",
                            ShopId = 24
                        },
                        new
                        {
                            Id = 25,
                            Email = "spadillao@webeden.co.uk",
                            FirstName = "Siobhan",
                            LastName = "Padilla",
                            ShopId = 25
                        },
                        new
                        {
                            Id = 26,
                            Email = "tmackeigp@eventbrite.com",
                            FirstName = "Tobi",
                            LastName = "MacKeig",
                            ShopId = 26
                        },
                        new
                        {
                            Id = 27,
                            Email = "sbeldhamq@eventbrite.com",
                            FirstName = "Sonnie",
                            LastName = "Beldham",
                            ShopId = 27
                        },
                        new
                        {
                            Id = 28,
                            Email = "apreatorr@techcrunch.com",
                            FirstName = "Alexis",
                            LastName = "Preator",
                            ShopId = 28
                        },
                        new
                        {
                            Id = 29,
                            Email = "sedinboroughs@bloomberg.com",
                            FirstName = "Sondra",
                            LastName = "Edinborough",
                            ShopId = 29
                        },
                        new
                        {
                            Id = 30,
                            Email = "mkillinert@naver.com",
                            FirstName = "Moses",
                            LastName = "Killiner",
                            ShopId = 30
                        },
                        new
                        {
                            Id = 31,
                            Email = "aliffeyu@wix.com",
                            FirstName = "Andriette",
                            LastName = "Liffey",
                            ShopId = 31
                        },
                        new
                        {
                            Id = 32,
                            Email = "nkenchv@mit.edu",
                            FirstName = "Nickola",
                            LastName = "Kench",
                            ShopId = 32
                        },
                        new
                        {
                            Id = 33,
                            Email = "kpechtw@free.fr",
                            FirstName = "Kerby",
                            LastName = "Pecht",
                            ShopId = 33
                        },
                        new
                        {
                            Id = 34,
                            Email = "pverricox@redcross.org",
                            FirstName = "Prinz",
                            LastName = "Verrico",
                            ShopId = 34
                        },
                        new
                        {
                            Id = 35,
                            Email = "bferrey@unc.edu",
                            FirstName = "Byrom",
                            LastName = "Ferre",
                            ShopId = 35
                        },
                        new
                        {
                            Id = 36,
                            Email = "tbuckleez@netlog.com",
                            FirstName = "Tracy",
                            LastName = "Bucklee",
                            ShopId = 36
                        },
                        new
                        {
                            Id = 37,
                            Email = "bpapis10@wordpress.com",
                            FirstName = "Bryan",
                            LastName = "Papis",
                            ShopId = 37
                        },
                        new
                        {
                            Id = 38,
                            Email = "lduffil11@mapquest.com",
                            FirstName = "Leonhard",
                            LastName = "Duffil",
                            ShopId = 38
                        },
                        new
                        {
                            Id = 39,
                            Email = "amcilenna12@gnu.org",
                            FirstName = "Agnes",
                            LastName = "McIlenna",
                            ShopId = 39
                        },
                        new
                        {
                            Id = 40,
                            Email = "pskerman13@t.co",
                            FirstName = "Prentice",
                            LastName = "Skerman",
                            ShopId = 40
                        },
                        new
                        {
                            Id = 41,
                            Email = "amcbride14@uiuc.edu",
                            FirstName = "Amity",
                            LastName = "McBride",
                            ShopId = 41
                        },
                        new
                        {
                            Id = 42,
                            Email = "gtrumper15@google.fr",
                            FirstName = "Georgie",
                            LastName = "Trumper",
                            ShopId = 42
                        },
                        new
                        {
                            Id = 43,
                            Email = "odumbare16@gnu.org",
                            FirstName = "Orelee",
                            LastName = "Dumbare",
                            ShopId = 43
                        },
                        new
                        {
                            Id = 44,
                            Email = "btroyes17@ebay.co.uk",
                            FirstName = "Berny",
                            LastName = "Troyes",
                            ShopId = 44
                        },
                        new
                        {
                            Id = 45,
                            Email = "tchiverstone18@jiathis.com",
                            FirstName = "Tobias",
                            LastName = "Chiverstone",
                            ShopId = 45
                        },
                        new
                        {
                            Id = 46,
                            Email = "wesposita19@ebay.com",
                            FirstName = "Wandis",
                            LastName = "Esposita",
                            ShopId = 46
                        },
                        new
                        {
                            Id = 47,
                            Email = "rbau1a@printfriendly.com",
                            FirstName = "Rachel",
                            LastName = "Bau",
                            ShopId = 47
                        },
                        new
                        {
                            Id = 48,
                            Email = "vkondratenya1b@blinklist.com",
                            FirstName = "Virgie",
                            LastName = "Kondratenya",
                            ShopId = 48
                        },
                        new
                        {
                            Id = 49,
                            Email = "rmcdonough1c@oaic.gov.au",
                            FirstName = "Rhianna",
                            LastName = "McDonough",
                            ShopId = 49
                        },
                        new
                        {
                            Id = 50,
                            Email = "mbingle1d@msn.com",
                            FirstName = "Mayer",
                            LastName = "Bingle",
                            ShopId = 50
                        },
                        new
                        {
                            Id = 51,
                            Email = "aashment1e@usatoday.com",
                            FirstName = "Antonetta",
                            LastName = "Ashment",
                            ShopId = 51
                        },
                        new
                        {
                            Id = 52,
                            Email = "twildblood1f@360.cn",
                            FirstName = "Tanhya",
                            LastName = "Wildblood",
                            ShopId = 52
                        },
                        new
                        {
                            Id = 53,
                            Email = "dmcauley1g@aboutads.info",
                            FirstName = "Danella",
                            LastName = "McAuley",
                            ShopId = 53
                        },
                        new
                        {
                            Id = 54,
                            Email = "gtchir1h@dion.ne.jp",
                            FirstName = "Grethel",
                            LastName = "Tchir",
                            ShopId = 54
                        },
                        new
                        {
                            Id = 55,
                            Email = "amcevoy1i@wordpress.org",
                            FirstName = "Araldo",
                            LastName = "McEvoy",
                            ShopId = 55
                        },
                        new
                        {
                            Id = 56,
                            Email = "bluckwell1j@engadget.com",
                            FirstName = "Belva",
                            LastName = "Luckwell",
                            ShopId = 56
                        },
                        new
                        {
                            Id = 57,
                            Email = "chellyar1k@businesswire.com",
                            FirstName = "Carolina",
                            LastName = "Hellyar",
                            ShopId = 57
                        },
                        new
                        {
                            Id = 58,
                            Email = "ebubbear1l@wordpress.org",
                            FirstName = "Eamon",
                            LastName = "Bubbear",
                            ShopId = 58
                        },
                        new
                        {
                            Id = 59,
                            Email = "rdumbreck1m@indiegogo.com",
                            FirstName = "Rachel",
                            LastName = "Dumbreck",
                            ShopId = 59
                        },
                        new
                        {
                            Id = 60,
                            Email = "jduncan1n@illinois.edu",
                            FirstName = "Jobyna",
                            LastName = "Duncan",
                            ShopId = 60
                        },
                        new
                        {
                            Id = 61,
                            Email = "mravel1o@mtv.com",
                            FirstName = "Marney",
                            LastName = "Ravel",
                            ShopId = 61
                        },
                        new
                        {
                            Id = 62,
                            Email = "amcshee1p@vimeo.com",
                            FirstName = "Allin",
                            LastName = "McShee",
                            ShopId = 62
                        },
                        new
                        {
                            Id = 63,
                            Email = "okersaw1q@fastcompany.com",
                            FirstName = "Orelie",
                            LastName = "Kersaw",
                            ShopId = 63
                        },
                        new
                        {
                            Id = 64,
                            Email = "maxelbey1r@ft.com",
                            FirstName = "Madison",
                            LastName = "Axelbey",
                            ShopId = 64
                        },
                        new
                        {
                            Id = 65,
                            Email = "dbreckenridge1s@buzzfeed.com",
                            FirstName = "Darren",
                            LastName = "Breckenridge",
                            ShopId = 65
                        },
                        new
                        {
                            Id = 66,
                            Email = "egosnoll1t@ihg.com",
                            FirstName = "Eldridge",
                            LastName = "Gosnoll",
                            ShopId = 66
                        },
                        new
                        {
                            Id = 67,
                            Email = "rgratland1u@bigcartel.com",
                            FirstName = "Roderich",
                            LastName = "Gratland",
                            ShopId = 67
                        },
                        new
                        {
                            Id = 68,
                            Email = "cfrederick1v@comcast.net",
                            FirstName = "Christoforo",
                            LastName = "Frederick",
                            ShopId = 68
                        },
                        new
                        {
                            Id = 69,
                            Email = "hbeamand1w@alibaba.com",
                            FirstName = "Heath",
                            LastName = "Beamand",
                            ShopId = 69
                        },
                        new
                        {
                            Id = 70,
                            Email = "astammirs1x@mysql.com",
                            FirstName = "Andros",
                            LastName = "Stammirs",
                            ShopId = 70
                        },
                        new
                        {
                            Id = 71,
                            Email = "mrupert1y@purevolume.com",
                            FirstName = "Merola",
                            LastName = "Rupert",
                            ShopId = 71
                        },
                        new
                        {
                            Id = 72,
                            Email = "ccracie1z@google.com.hk",
                            FirstName = "Caryn",
                            LastName = "Cracie",
                            ShopId = 72
                        },
                        new
                        {
                            Id = 73,
                            Email = "gedinburgh20@comcast.net",
                            FirstName = "Georgina",
                            LastName = "Edinburgh",
                            ShopId = 73
                        },
                        new
                        {
                            Id = 74,
                            Email = "skeveren21@vk.com",
                            FirstName = "Saunders",
                            LastName = "Keveren",
                            ShopId = 74
                        },
                        new
                        {
                            Id = 75,
                            Email = "mscarman22@pbs.org",
                            FirstName = "Milissent",
                            LastName = "Scarman",
                            ShopId = 75
                        },
                        new
                        {
                            Id = 76,
                            Email = "glethebridge23@wiley.com",
                            FirstName = "Giana",
                            LastName = "Lethebridge",
                            ShopId = 76
                        });
                });

            modelBuilder.Entity("Shops.DataAccess.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CountryId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 10,
                            CountryId = 1,
                            Email = "Berlin@detego.com",
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Hamburg@detego.com",
                            Name = "Hamburg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "München@detego.com",
                            Name = "München"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Köln@detego.com",
                            Name = "Köln"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            CountryId = 1,
                            Email = "Frankfurt@detego.com",
                            Name = "Frankfurt am Main"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Stuttgart@detego.com",
                            Name = "Stuttgart"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Düsseldorf@detego.com",
                            Name = "Düsseldorf"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Dortmund@detego.com",
                            Name = "Dortmund"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Essen@detego.com",
                            Name = "Essen"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Bremen@detego.com",
                            Name = "Bremen"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Leipzig@detego.com",
                            Name = "Leipzig"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            CountryId = 1,
                            Email = "Dresden@detego.com",
                            Name = "Dresden"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            CountryId = 1,
                            Email = "Hannover@detego.com",
                            Name = "Hannover"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Nürnberg@detego.com",
                            Name = "Nürnberg"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Duisburg@detego.com",
                            Name = "Duisburg"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Bochum@detego.com",
                            Name = "Bochum"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Wuppertal@detego.com",
                            Name = "Wuppertal"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Bielefeld@detego.com",
                            Name = "Bielefeld"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Bonn@detego.com",
                            Name = "Bonn"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Münster@detego.com",
                            Name = "Münster"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Karlsruhe@detego.com",
                            Name = "Karlsruhe"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Mannheim@detego.com",
                            Name = "Mannheim"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Augsburg@detego.com",
                            Name = "Augsburg"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Wiesbaden@detego.com",
                            Name = "Wiesbaden"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Gelsenkirchen@detego.com",
                            Name = "Gelsenkirchen"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Mönchengladbach@detego.com",
                            Name = "Mönchengladbach"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Braunschweig@detego.com",
                            Name = "Braunschweig"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Chemnitz@detego.com",
                            Name = "Chemnitz"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Aachen@detego.com",
                            Name = "Aachen"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Kiel@detego.com",
                            Name = "Kiel"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Halle@detego.com",
                            Name = "Halle (Saale)"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Magdeburg@detego.com",
                            Name = "Magdeburg"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Krefeld@detego.com",
                            Name = "Krefeld"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Freiburg@detego.com",
                            Name = "Freiburg im Breisgau"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Lübeck@detego.com",
                            Name = "Lübeck"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Oberhausen@detego.com",
                            Name = "Oberhausen"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Erfurt@detego.com",
                            Name = "Erfurt"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Mainz@detego.com",
                            Name = "Mainz"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Rostock@detego.com",
                            Name = "Rostock"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Kassel@detego.com",
                            Name = "Kassel"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Hagen@detego.com",
                            Name = "Hagen"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Saarbrücken@detego.com",
                            Name = "Saarbrücken"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Hamm@detego.com",
                            Name = "Hamm"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Mülheim@detego.com",
                            Name = "Mülheim an der Ruhr"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Ludwigshafen@detego.com",
                            Name = "Ludwigshafen am Rhein"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Potsdam@detego.com",
                            Name = "Potsdam"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Leverkusen@detego.com",
                            Name = "Leverkusen"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Oldenburg@detego.com",
                            Name = "Oldenburg"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Osnabrück@detego.com",
                            Name = "Osnabrück"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Solingen@detego.com",
                            Name = "Solingen"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Herne@detego.com",
                            Name = "Herne"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Neuss@detego.com",
                            Name = "Neuss"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Heidelberg@detego.com",
                            Name = "Heidelberg"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Darmstadt@detego.com",
                            Name = "Darmstadt"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Paderborn@detego.com",
                            Name = "Paderborn"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Regensburg@detego.com",
                            Name = "Regensburg"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 2,
                            CountryId = 1,
                            Email = "Ingolstadt@detego.com",
                            Name = "Ingolstadt"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Würzburg@detego.com",
                            Name = "Würzburg"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Wolfsburg@detego.com",
                            Name = "Wolfsburg"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Fürth@detego.com",
                            Name = "Fürth"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Ulm@detego.com",
                            Name = "Ulm"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Offenbach@detego.com",
                            Name = "Offenbach am Main"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Heilbronn@detego.com",
                            Name = "Heilbronn"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Pforzheim@detego.com",
                            Name = "Pforzheim"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Göttingen@detego.com",
                            Name = "Göttingen"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Bottrop@detego.com",
                            Name = "Bottrop"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Recklinghausen@detego.com",
                            Name = "Recklinghausen"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 2,
                            CountryId = 1,
                            Email = "Reutlingen@detego.com",
                            Name = "Reutlingen"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Koblenz@detego.com",
                            Name = "Koblenz"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 2,
                            CountryId = 1,
                            Email = "BergischGladbach@detego.com",
                            Name = "Bergisch Gladbach"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Remscheid@detego.com",
                            Name = "Remscheid"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 4,
                            CountryId = 1,
                            Email = "Bremerhaven@detego.com",
                            Name = "Bremerhaven"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 3,
                            CountryId = 1,
                            Email = "Jena@detego.com",
                            Name = "Jena"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 6,
                            CountryId = 1,
                            Email = "Trier@detego.com",
                            Name = "Trier"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 5,
                            CountryId = 1,
                            Email = "Erlangen@detego.com",
                            Name = "Erlangen"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 2,
                            CountryId = 1,
                            Email = "Moers@detego.com",
                            Name = "Moers"
                        });
                });

            modelBuilder.Entity("Shops.DataAccess.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Accuracy")
                        .HasColumnType("real");

                    b.Property<long>("Backstore")
                        .HasColumnType("bigint");

                    b.Property<long>("Frontstore")
                        .HasColumnType("bigint");

                    b.Property<int>("MeanAge")
                        .HasColumnType("integer");

                    b.Property<float>("OnFloorAvailability")
                        .HasColumnType("real");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<int>("ShoppingWindow")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accuracy = 0.946f,
                            Backstore = 1514L,
                            Frontstore = 5865L,
                            MeanAge = 13,
                            OnFloorAvailability = 0.888f,
                            ShopId = 1,
                            ShoppingWindow = 43
                        },
                        new
                        {
                            Id = 2,
                            Accuracy = 0.806f,
                            Backstore = 863L,
                            Frontstore = 2581L,
                            MeanAge = 11,
                            OnFloorAvailability = 0.999f,
                            ShopId = 2,
                            ShoppingWindow = 18
                        },
                        new
                        {
                            Id = 3,
                            Accuracy = 0.987f,
                            Backstore = 1195L,
                            Frontstore = 4309L,
                            MeanAge = 7,
                            OnFloorAvailability = 0.945f,
                            ShopId = 3,
                            ShoppingWindow = 9
                        },
                        new
                        {
                            Id = 4,
                            Accuracy = 0.902f,
                            Backstore = 876L,
                            Frontstore = 4259L,
                            MeanAge = 10,
                            OnFloorAvailability = 0.936f,
                            ShopId = 4,
                            ShoppingWindow = 12
                        },
                        new
                        {
                            Id = 5,
                            Accuracy = 0.971f,
                            Backstore = 965L,
                            Frontstore = 2815L,
                            MeanAge = 8,
                            OnFloorAvailability = 0.965f,
                            ShopId = 5,
                            ShoppingWindow = 7
                        },
                        new
                        {
                            Id = 6,
                            Accuracy = 0.837f,
                            Backstore = 733L,
                            Frontstore = 2089L,
                            MeanAge = 5,
                            OnFloorAvailability = 0.984f,
                            ShopId = 6,
                            ShoppingWindow = 21
                        },
                        new
                        {
                            Id = 7,
                            Accuracy = 0.889f,
                            Backstore = 999L,
                            Frontstore = 3065L,
                            MeanAge = 8,
                            OnFloorAvailability = 0.827f,
                            ShopId = 7,
                            ShoppingWindow = 16
                        },
                        new
                        {
                            Id = 8,
                            Accuracy = 0.826f,
                            Backstore = 512L,
                            Frontstore = 2378L,
                            MeanAge = 5,
                            OnFloorAvailability = 0.943f,
                            ShopId = 8,
                            ShoppingWindow = 20
                        },
                        new
                        {
                            Id = 9,
                            Accuracy = 0.975f,
                            Backstore = 1041L,
                            Frontstore = 3782L,
                            MeanAge = 15,
                            OnFloorAvailability = 0.917f,
                            ShopId = 9,
                            ShoppingWindow = 28
                        },
                        new
                        {
                            Id = 10,
                            Accuracy = 0.817f,
                            Backstore = 319L,
                            Frontstore = 1794L,
                            MeanAge = 14,
                            OnFloorAvailability = 0.808f,
                            ShopId = 10,
                            ShoppingWindow = 4
                        },
                        new
                        {
                            Id = 11,
                            Accuracy = 0.975f,
                            Backstore = 537L,
                            Frontstore = 2853L,
                            MeanAge = 15,
                            OnFloorAvailability = 0.962f,
                            ShopId = 11,
                            ShoppingWindow = 20
                        },
                        new
                        {
                            Id = 12,
                            Accuracy = 0.894f,
                            Backstore = 732L,
                            Frontstore = 4261L,
                            MeanAge = 15,
                            OnFloorAvailability = 0.999f,
                            ShopId = 12,
                            ShoppingWindow = 18
                        },
                        new
                        {
                            Id = 13,
                            Accuracy = 0.902f,
                            Backstore = 753L,
                            Frontstore = 3277L,
                            MeanAge = 6,
                            OnFloorAvailability = 0.848f,
                            ShopId = 13,
                            ShoppingWindow = 9
                        },
                        new
                        {
                            Id = 14,
                            Accuracy = 0.979f,
                            Backstore = 825L,
                            Frontstore = 3715L,
                            MeanAge = 13,
                            OnFloorAvailability = 0.835f,
                            ShopId = 14,
                            ShoppingWindow = 9
                        },
                        new
                        {
                            Id = 15,
                            Accuracy = 0.922f,
                            Backstore = 682L,
                            Frontstore = 2501L,
                            MeanAge = 12,
                            OnFloorAvailability = 0.899f,
                            ShopId = 15,
                            ShoppingWindow = 17
                        },
                        new
                        {
                            Id = 16,
                            Accuracy = 0.949f,
                            Backstore = 954L,
                            Frontstore = 3605L,
                            MeanAge = 5,
                            OnFloorAvailability = 0.872f,
                            ShopId = 16,
                            ShoppingWindow = 5
                        },
                        new
                        {
                            Id = 17,
                            Accuracy = 0.804f,
                            Backstore = 910L,
                            Frontstore = 3258L,
                            MeanAge = 10,
                            OnFloorAvailability = 0.958f,
                            ShopId = 17,
                            ShoppingWindow = 13
                        },
                        new
                        {
                            Id = 18,
                            Accuracy = 0.987f,
                            Backstore = 776L,
                            Frontstore = 2255L,
                            MeanAge = 11,
                            OnFloorAvailability = 0.896f,
                            ShopId = 18,
                            ShoppingWindow = 14
                        },
                        new
                        {
                            Id = 19,
                            Accuracy = 0.946f,
                            Backstore = 1074L,
                            Frontstore = 4358L,
                            MeanAge = 6,
                            OnFloorAvailability = 0.965f,
                            ShopId = 19,
                            ShoppingWindow = 25
                        },
                        new
                        {
                            Id = 20,
                            Accuracy = 0.99f,
                            Backstore = 798L,
                            Frontstore = 3223L,
                            MeanAge = 9,
                            OnFloorAvailability = 0.873f,
                            ShopId = 20,
                            ShoppingWindow = 9
                        },
                        new
                        {
                            Id = 21,
                            Accuracy = 0.91f,
                            Backstore = 1011L,
                            Frontstore = 3873L,
                            MeanAge = 5,
                            OnFloorAvailability = 0.882f,
                            ShopId = 21,
                            ShoppingWindow = 7
                        },
                        new
                        {
                            Id = 22,
                            Accuracy = 0.899f,
                            Backstore = 555L,
                            Frontstore = 2147L,
                            MeanAge = 12,
                            OnFloorAvailability = 0.815f,
                            ShopId = 22,
                            ShoppingWindow = 9
                        },
                        new
                        {
                            Id = 23,
                            Accuracy = 0.844f,
                            Backstore = 602L,
                            Frontstore = 3127L,
                            MeanAge = 10,
                            OnFloorAvailability = 0.801f,
                            ShopId = 23,
                            ShoppingWindow = 15
                        },
                        new
                        {
                            Id = 24,
                            Accuracy = 0.824f,
                            Backstore = 561L,
                            Frontstore = 2374L,
                            MeanAge = 14,
                            OnFloorAvailability = 0.814f,
                            ShopId = 24,
                            ShoppingWindow = 20
                        },
                        new
                        {
                            Id = 25,
                            Accuracy = 0.95f,
                            Backstore = 990L,
                            Frontstore = 4113L,
                            MeanAge = 14,
                            OnFloorAvailability = 0.891f,
                            ShopId = 25,
                            ShoppingWindow = 9
                        },
                        new
                        {
                            Id = 26,
                            Accuracy = 0.837f,
                            Backstore = 391L,
                            Frontstore = 2226L,
                            MeanAge = 7,
                            OnFloorAvailability = 0.973f,
                            ShopId = 26,
                            ShoppingWindow = 8
                        },
                        new
                        {
                            Id = 27,
                            Accuracy = 0.951f,
                            Backstore = 729L,
                            Frontstore = 3401L,
                            MeanAge = 15,
                            OnFloorAvailability = 0.865f,
                            ShopId = 27,
                            ShoppingWindow = 13
                        },
                        new
                        {
                            Id = 28,
                            Accuracy = 0.825f,
                            Backstore = 493L,
                            Frontstore = 3120L,
                            MeanAge = 5,
                            OnFloorAvailability = 0.922f,
                            ShopId = 28,
                            ShoppingWindow = 13
                        },
                        new
                        {
                            Id = 29,
                            Accuracy = 0.885f,
                            Backstore = 568L,
                            Frontstore = 2398L,
                            MeanAge = 11,
                            OnFloorAvailability = 0.861f,
                            ShopId = 29,
                            ShoppingWindow = 10
                        },
                        new
                        {
                            Id = 30,
                            Accuracy = 0.856f,
                            Backstore = 436L,
                            Frontstore = 1718L,
                            MeanAge = 8,
                            OnFloorAvailability = 0.879f,
                            ShopId = 30,
                            ShoppingWindow = 8
                        },
                        new
                        {
                            Id = 31,
                            Accuracy = 0.981f,
                            Backstore = 559L,
                            Frontstore = 3025L,
                            MeanAge = 15,
                            OnFloorAvailability = 0.96f,
                            ShopId = 31,
                            ShoppingWindow = 13
                        },
                        new
                        {
                            Id = 32,
                            Accuracy = 0.942f,
                            Backstore = 809L,
                            Frontstore = 2141L,
                            MeanAge = 5,
                            OnFloorAvailability = 0.983f,
                            ShopId = 32,
                            ShoppingWindow = 11
                        },
                        new
                        {
                            Id = 33,
                            Accuracy = 0.806f,
                            Backstore = 683L,
                            Frontstore = 3874L,
                            MeanAge = 12,
                            OnFloorAvailability = 0.843f,
                            ShopId = 33,
                            ShoppingWindow = 17
                        },
                        new
                        {
                            Id = 34,
                            Accuracy = 0.981f,
                            Backstore = 1185L,
                            Frontstore = 2417L,
                            MeanAge = 5,
                            OnFloorAvailability = 0.984f,
                            ShopId = 34,
                            ShoppingWindow = 19
                        },
                        new
                        {
                            Id = 35,
                            Accuracy = 0.814f,
                            Backstore = 611L,
                            Frontstore = 3292L,
                            MeanAge = 8,
                            OnFloorAvailability = 0.922f,
                            ShopId = 35,
                            ShoppingWindow = 8
                        },
                        new
                        {
                            Id = 36,
                            Accuracy = 0.872f,
                            Backstore = 523L,
                            Frontstore = 2646L,
                            MeanAge = 8,
                            OnFloorAvailability = 0.948f,
                            ShopId = 36,
                            ShoppingWindow = 12
                        },
                        new
                        {
                            Id = 37,
                            Accuracy = 0.992f,
                            Backstore = 792L,
                            Frontstore = 2086L,
                            MeanAge = 7,
                            OnFloorAvailability = 0.841f,
                            ShopId = 37,
                            ShoppingWindow = 10
                        },
                        new
                        {
                            Id = 38,
                            Accuracy = 0.927f,
                            Backstore = 469L,
                            Frontstore = 1729L,
                            MeanAge = 9,
                            OnFloorAvailability = 0.863f,
                            ShopId = 38,
                            ShoppingWindow = 3
                        },
                        new
                        {
                            Id = 39,
                            Accuracy = 0.966f,
                            Backstore = 720L,
                            Frontstore = 3228L,
                            MeanAge = 12,
                            OnFloorAvailability = 0.877f,
                            ShopId = 39,
                            ShoppingWindow = 16
                        },
                        new
                        {
                            Id = 40,
                            Accuracy = 0.907f,
                            Backstore = 565L,
                            Frontstore = 2315L,
                            MeanAge = 8,
                            OnFloorAvailability = 0.849f,
                            ShopId = 40,
                            ShoppingWindow = 13
                        },
                        new
                        {
                            Id = 41,
                            Accuracy = 0.955f,
                            Backstore = 885L,
                            Frontstore = 3354L,
                            MeanAge = 12,
                            OnFloorAvailability = 0.963f,
                            ShopId = 41,
                            ShoppingWindow = 6
                        },
                        new
                        {
                            Id = 42,
                            Accuracy = 0.894f,
                            Backstore = 735L,
                            Frontstore = 2443L,
                            MeanAge = 11,
                            OnFloorAvailability = 0.84f,
                            ShopId = 42,
                            ShoppingWindow = 16
                        },
                        new
                        {
                            Id = 43,
                            Accuracy = 0.869f,
                            Backstore = 970L,
                            Frontstore = 3174L,
                            MeanAge = 12,
                            OnFloorAvailability = 0.967f,
                            ShopId = 43,
                            ShoppingWindow = 18
                        },
                        new
                        {
                            Id = 44,
                            Accuracy = 0.922f,
                            Backstore = 540L,
                            Frontstore = 2840L,
                            MeanAge = 6,
                            OnFloorAvailability = 0.982f,
                            ShopId = 44,
                            ShoppingWindow = 10
                        },
                        new
                        {
                            Id = 45,
                            Accuracy = 0.805f,
                            Backstore = 1105L,
                            Frontstore = 3994L,
                            MeanAge = 13,
                            OnFloorAvailability = 0.951f,
                            ShopId = 45,
                            ShoppingWindow = 23
                        },
                        new
                        {
                            Id = 46,
                            Accuracy = 0.933f,
                            Backstore = 643L,
                            Frontstore = 3909L,
                            MeanAge = 8,
                            OnFloorAvailability = 0.983f,
                            ShopId = 46,
                            ShoppingWindow = 9
                        },
                        new
                        {
                            Id = 47,
                            Accuracy = 0.987f,
                            Backstore = 987L,
                            Frontstore = 4561L,
                            MeanAge = 14,
                            OnFloorAvailability = 0.999f,
                            ShopId = 47,
                            ShoppingWindow = 22
                        },
                        new
                        {
                            Id = 48,
                            Accuracy = 0.838f,
                            Backstore = 405L,
                            Frontstore = 2320L,
                            MeanAge = 7,
                            OnFloorAvailability = 0.916f,
                            ShopId = 48,
                            ShoppingWindow = 9
                        },
                        new
                        {
                            Id = 49,
                            Accuracy = 0.857f,
                            Backstore = 767L,
                            Frontstore = 4289L,
                            MeanAge = 15,
                            OnFloorAvailability = 0.805f,
                            ShopId = 49,
                            ShoppingWindow = 23
                        },
                        new
                        {
                            Id = 50,
                            Accuracy = 0.958f,
                            Backstore = 329L,
                            Frontstore = 1697L,
                            MeanAge = 7,
                            OnFloorAvailability = 0.982f,
                            ShopId = 50,
                            ShoppingWindow = 6
                        },
                        new
                        {
                            Id = 51,
                            Accuracy = 0.928f,
                            Backstore = 552L,
                            Frontstore = 2209L,
                            MeanAge = 8,
                            OnFloorAvailability = 0.819f,
                            ShopId = 51,
                            ShoppingWindow = 12
                        },
                        new
                        {
                            Id = 52,
                            Accuracy = 0.978f,
                            Backstore = 535L,
                            Frontstore = 3581L,
                            MeanAge = 9,
                            OnFloorAvailability = 0.881f,
                            ShopId = 52,
                            ShoppingWindow = 11
                        },
                        new
                        {
                            Id = 53,
                            Accuracy = 0.939f,
                            Backstore = 796L,
                            Frontstore = 2394L,
                            MeanAge = 8,
                            OnFloorAvailability = 0.804f,
                            ShopId = 53,
                            ShoppingWindow = 11
                        },
                        new
                        {
                            Id = 54,
                            Accuracy = 0.886f,
                            Backstore = 314L,
                            Frontstore = 2331L,
                            MeanAge = 5,
                            OnFloorAvailability = 0.808f,
                            ShopId = 54,
                            ShoppingWindow = 11
                        },
                        new
                        {
                            Id = 55,
                            Accuracy = 0.896f,
                            Backstore = 978L,
                            Frontstore = 3216L,
                            MeanAge = 5,
                            OnFloorAvailability = 0.942f,
                            ShopId = 55,
                            ShoppingWindow = 20
                        },
                        new
                        {
                            Id = 56,
                            Accuracy = 0.807f,
                            Backstore = 942L,
                            Frontstore = 2029L,
                            MeanAge = 5,
                            OnFloorAvailability = 0.86f,
                            ShopId = 56,
                            ShoppingWindow = 24
                        },
                        new
                        {
                            Id = 57,
                            Accuracy = 0.898f,
                            Backstore = 220L,
                            Frontstore = 1146L,
                            MeanAge = 9,
                            OnFloorAvailability = 0.821f,
                            ShopId = 57,
                            ShoppingWindow = 7
                        },
                        new
                        {
                            Id = 58,
                            Accuracy = 0.895f,
                            Backstore = 603L,
                            Frontstore = 3063L,
                            MeanAge = 10,
                            OnFloorAvailability = 0.92f,
                            ShopId = 58,
                            ShoppingWindow = 8
                        },
                        new
                        {
                            Id = 59,
                            Accuracy = 0.82f,
                            Backstore = 670L,
                            Frontstore = 1919L,
                            MeanAge = 14,
                            OnFloorAvailability = 0.929f,
                            ShopId = 59,
                            ShoppingWindow = 10
                        },
                        new
                        {
                            Id = 60,
                            Accuracy = 0.905f,
                            Backstore = 313L,
                            Frontstore = 1622L,
                            MeanAge = 9,
                            OnFloorAvailability = 0.982f,
                            ShopId = 60,
                            ShoppingWindow = 7
                        },
                        new
                        {
                            Id = 61,
                            Accuracy = 0.907f,
                            Backstore = 1183L,
                            Frontstore = 4766L,
                            MeanAge = 6,
                            OnFloorAvailability = 0.857f,
                            ShopId = 61,
                            ShoppingWindow = 21
                        },
                        new
                        {
                            Id = 62,
                            Accuracy = 0.833f,
                            Backstore = 814L,
                            Frontstore = 3391L,
                            MeanAge = 12,
                            OnFloorAvailability = 0.899f,
                            ShopId = 62,
                            ShoppingWindow = 23
                        },
                        new
                        {
                            Id = 63,
                            Accuracy = 0.815f,
                            Backstore = 537L,
                            Frontstore = 1311L,
                            MeanAge = 6,
                            OnFloorAvailability = 0.905f,
                            ShopId = 63,
                            ShoppingWindow = 13
                        },
                        new
                        {
                            Id = 64,
                            Accuracy = 0.983f,
                            Backstore = 556L,
                            Frontstore = 2102L,
                            MeanAge = 12,
                            OnFloorAvailability = 0.831f,
                            ShopId = 64,
                            ShoppingWindow = 19
                        },
                        new
                        {
                            Id = 65,
                            Accuracy = 0.863f,
                            Backstore = 981L,
                            Frontstore = 3820L,
                            MeanAge = 12,
                            OnFloorAvailability = 0.817f,
                            ShopId = 65,
                            ShoppingWindow = 27
                        },
                        new
                        {
                            Id = 66,
                            Accuracy = 0.926f,
                            Backstore = 672L,
                            Frontstore = 2775L,
                            MeanAge = 8,
                            OnFloorAvailability = 0.803f,
                            ShopId = 66,
                            ShoppingWindow = 21
                        },
                        new
                        {
                            Id = 67,
                            Accuracy = 0.846f,
                            Backstore = 676L,
                            Frontstore = 2384L,
                            MeanAge = 10,
                            OnFloorAvailability = 0.986f,
                            ShopId = 67,
                            ShoppingWindow = 6
                        },
                        new
                        {
                            Id = 68,
                            Accuracy = 0.817f,
                            Backstore = 333L,
                            Frontstore = 831L,
                            MeanAge = 14,
                            OnFloorAvailability = 0.895f,
                            ShopId = 68,
                            ShoppingWindow = 5
                        },
                        new
                        {
                            Id = 69,
                            Accuracy = 0.855f,
                            Backstore = 875L,
                            Frontstore = 3306L,
                            MeanAge = 9,
                            OnFloorAvailability = 0.814f,
                            ShopId = 69,
                            ShoppingWindow = 19
                        },
                        new
                        {
                            Id = 70,
                            Accuracy = 0.85f,
                            Backstore = 296L,
                            Frontstore = 1442L,
                            MeanAge = 8,
                            OnFloorAvailability = 0.969f,
                            ShopId = 70,
                            ShoppingWindow = 3
                        },
                        new
                        {
                            Id = 71,
                            Accuracy = 0.966f,
                            Backstore = 400L,
                            Frontstore = 3025L,
                            MeanAge = 14,
                            OnFloorAvailability = 0.929f,
                            ShopId = 71,
                            ShoppingWindow = 5
                        },
                        new
                        {
                            Id = 72,
                            Accuracy = 0.839f,
                            Backstore = 712L,
                            Frontstore = 2884L,
                            MeanAge = 10,
                            OnFloorAvailability = 0.866f,
                            ShopId = 72,
                            ShoppingWindow = 10
                        },
                        new
                        {
                            Id = 73,
                            Accuracy = 0.874f,
                            Backstore = 540L,
                            Frontstore = 2164L,
                            MeanAge = 6,
                            OnFloorAvailability = 0.829f,
                            ShopId = 73,
                            ShoppingWindow = 3
                        },
                        new
                        {
                            Id = 74,
                            Accuracy = 0.841f,
                            Backstore = 892L,
                            Frontstore = 3211L,
                            MeanAge = 5,
                            OnFloorAvailability = 0.869f,
                            ShopId = 74,
                            ShoppingWindow = 7
                        },
                        new
                        {
                            Id = 75,
                            Accuracy = 0.96f,
                            Backstore = 567L,
                            Frontstore = 2127L,
                            MeanAge = 7,
                            OnFloorAvailability = 0.915f,
                            ShopId = 75,
                            ShoppingWindow = 16
                        },
                        new
                        {
                            Id = 76,
                            Accuracy = 0.85f,
                            Backstore = 253L,
                            Frontstore = 1475L,
                            MeanAge = 9,
                            OnFloorAvailability = 0.957f,
                            ShopId = 76,
                            ShoppingWindow = 9
                        });
                });

            modelBuilder.Entity("Shops.DataAccess.Entities.Manager", b =>
                {
                    b.HasOne("Shops.DataAccess.Entities.Shop", "Shop")
                        .WithOne("Manager")
                        .HasForeignKey("Shops.DataAccess.Entities.Manager", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Shops.DataAccess.Entities.Shop", b =>
                {
                    b.HasOne("Shops.DataAccess.Entities.Category", "Category")
                        .WithMany("Shops")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shops.DataAccess.Entities.Country", "Country")
                        .WithMany("Shops")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Shops.DataAccess.Entities.Stock", b =>
                {
                    b.HasOne("Shops.DataAccess.Entities.Shop", "Shop")
                        .WithOne("Stock")
                        .HasForeignKey("Shops.DataAccess.Entities.Stock", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Shops.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Shops");
                });

            modelBuilder.Entity("Shops.DataAccess.Entities.Country", b =>
                {
                    b.Navigation("Shops");
                });

            modelBuilder.Entity("Shops.DataAccess.Entities.Shop", b =>
                {
                    b.Navigation("Manager")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
